### ISSUE TITLE
Release the whole project source code

### ISSUE THREAD

**Issue by sunstarchan** [Franpin/TopoLogic#1]
First of all, I'd glad to say this is a great idea about topology reasoning and thanks for opening the source code.

I noticed that there was only openlanev2 related code in the latest commit. So I was wondering the whole project source code. 
I checked all the commits and got the changes with TopoNet, but I still confused about the functions you added in `openlanev2/centerline/evaluation/evaluate.py`. They were be called in somewhere, unfortunately I could find it.

**Comment by Franpin** [comment]
Thank you for your discovery and suggestions. I am currently organizing the code and it will soon be open source. The change in openlanev2/centerline/evaluation/evaluate.py is based on the official code of openlanev2, it can be find in https://github.com/OpenDriveLab/OpenLane-V2/commit/5201bc220953f24c6993dbed98f4cc378c22d623
