### ISSUE TITLE
关于Lane Topology Head中learnable高斯函数细节

### ISSUE THREAD

**Issue by Yifeng-Bai** [Franpin/TopoLogic#6]
您好，很感谢您对Topo任务的创新，我现在对learnable高斯函数的细节有两个问题：
1. 请问code中的learnable高斯函数的超参数为什么初始化的和paper中的不一致呢
https://github.com/Franpin/TopoLogic/blob/68e0a8691580808393569d585d63e453b6918cb6/projects/topologic/models/modules/sgnn_decoder.py#L25-L28

2. 请问这里计算的std为什么没有在高斯函数中使用，但是多乘了一项topo_mask
https://github.com/Franpin/TopoLogic/blob/68e0a8691580808393569d585d63e453b6918cb6/projects/topologic/models/modules/sgnn_decoder.py#L95-L98

**Comment by Franpin** [comment]
非常感谢你的关注，在代码里没有把方差sigma放进去，代码里的self.w表示论文里sigma和lamda相乘的结果，为了方便，代码里将两者相乘的结果进行初始化，topo_mask是个对角矩阵，表示同一个lane之间没有topo关系，所以我们显式的乘以一个topo_mask。
