### ISSUE TITLE
Hello, may I ask how SDMap is used in your paper? I don't see it in the code?

### ISSUE THREAD

**Issue by missTL** [Franpin/TopoLogic#7]
![Uploading image.png…]()

**Comment by missTL** [comment]
![image](https://github.com/user-attachments/assets/c29c4886-59e0-4bfd-94da-3e7c97a1d2d4)

**Comment by Franpin** [comment]
The SMERF version of topologic in the paper is implemented under the SMERF framework, and if you are interested in this result, you can modify it in the SMERF code.
